### ISSUE TITLE
Running app locally, but storing data on GCloud

### ISSUE THREAD

**Issue by mtmarsh2** [onejgordon/flow-dashboard#115]
Hi, was wondering if its possible to run the app locally, but then actually store the data on Google Cloud. I know that running dev_appserver.py will run the app locally, and create a local data store that holds the data. I also know that running the deploy script will push the app to a server that isn't local, but will store the data in Gcloud. Is there a way to do a mix of the two?

**Comment by onejgordon** [comment]
With some development the app could be updated to call Google datastore or Google Cloud Storage APIs rather than store to the 'local' datastore. What would be the benefit of this? Seems like if privacy is a concern then this wouldn't be a significant improvement since data is still stored on Google's servers?
