### ISSUE TITLE
Alternative Sign In

### ISSUE THREAD

**Issue by krillin666** [onejgordon/flow-dashboard#139]
Hello,
This app checks all the requirments for the perfect app for habit tracking + todo-list with some nice integrations and it is open source.

However, for privacy reasons would it be possible to allow for non-google sign up ?

Thanks !

**Comment by onejgordon** [comment]
Earlier issue for this is here https://github.com/onejgordon/flow-dashboard/issues/124.
Would love to get to this as a priority issue, but no capacity at present. Very open to supporting someone to put in a PR, however, if there's interest out there.

Edit: Link fix

**Comment by bedlamzd** [comment]
if somebody is looking for the progress, it seems @onejgordon meant #124. At the time of me writing this comment, it's not started yet.

**Comment by onejgordon** [comment]
Thanks for that correction, @bedlamzd. 

Unfortunately, correct, no progress yet on alternative sign in. I will need to make an update to sign in flow shortly since Google is deprecating the old identity solution (https://developers.google.com/identity/sign-in/web/sign-in), but I don't think I'll have capacity just yet to add a password-based sign in. Open to a PR as always.
