### ISSUE TITLE
The Messenger bot does not provide clear assistance

### ISSUE THREAD

**Issue by JonTheNiceGuy** [onejgordon/flow-dashboard#45]
Here's an example exchange:

```
Me: daily report
Bot: A few words on your day?
Me: Busy but interesting
Bot: How was the day?
Me: Good
Bot: I couldn't understand your answer, please try again
Me: The day was good
Bot: I couldn't understand your answer, please try again
```

A better way to address it would be
```
Me: daily report
Bot: A few words on your day? [I'm looking for a narrative response]
Me: Busy but interesting
Bot: How was the day? [I'm looking for a number]
Me: 6
```

**Comment by onejgordon** [comment]
Agreed more guidance is needed.

Since the journal questions are user configurable, tacking on the instructions such as `i'm looking for a number` feels aggressive. I wonder if it would be sufficient to show the guidance in case of an uninterpretable response, e.g. `I couldn't understand your answer, please reply with a number (1-10)`

**Comment by JonTheNiceGuy** [comment]
That makes sense.
