### ISSUE TITLE
Add day of the week names to the habit tracker

### ISSUE THREAD

**Issue by Circuit8** [onejgordon/flow-dashboard#47]
![image](https://cloud.githubusercontent.com/assets/6171759/26148017/3b4d7d5c-3aed-11e7-98f1-4485ca5e7bf4.png)

Would be easier to use if you had 'Mon May 24' etc.

I'm happy to work on this.

**Comment by onejgordon** [comment]
I was just thinking about this today. We have a real-estate constraint, so I think keeping it small is good, maybe M T W Th F S Su format? 

We could also make the month numeric, since that's relatively redundant information, e.g. `W 5/17`. I wonder if this should be user configurable as well.

Happy to review a PR if you want to take a shot at this.

**Comment by Circuit8** [comment]
OK sounds good, I'm looking into this.
