### ISSUE TITLE
Add the ability to add journal entries at any time

### ISSUE THREAD

**Issue by Circuit8** [onejgordon/flow-dashboard#59]
Would be great if on the journal page there was a button to add an entry where you could select the date. Maybe I'm missing something but right now if you miss an entry for a day you can't add it later on.

**Comment by onejgordon** [comment]
Currently this is awkwardly supported. When within the journal window and viewing the journal entry dialog, there's a history icon at the top that allows you to fill in journals for days in the last week that weren't submitted. The journal history page then allows you to edit any historical journal you like.

This is limiting because if you're outside the journal window you can't submit current or historical entries. 

One possible solution is to allow the user to bring up the journal dialog at any time, and just use the journal window to prompt, but not restrict submission.

**Comment by onejgordon** [comment]
Resolved by https://github.com/onejgordon/flow-dashboard/commit/626744315e5c402566e3f24c9ad4682d679d568f
