### ISSUE TITLE
Snapshots analysis is empty

### ISSUE THREAD

**Issue by xverges** [onejgordon/flow-dashboard#79]
When I try to view the snapshots analysis, nothing happens. If I look under the hook, I see a successful call to https://flowdash.co/api/snapshot 

Possible anomalies in the returned JSON:

* `message` is null
* `metrics` is null for one of the elements of the `Snapshots` array (last one in the array)

The console reports `TypeError: e.metrics is null` so the second one looks like what is upsetting the client code.

**Comment by onejgordon** [comment]
Thanks for filing this @xverges. Symptom fixed in https://github.com/onejgordon/flow-dashboard/commit/df7e40f5f5b960d47252172551d893841c69509d, you can confirm on production now if analysis loads. 

I assume all snapshots were created from the Flow Snapshot android app and not from the API, is that right? Might have a bug in the app if a snapshot with null metrics was allowed.

**Comment by xverges** [comment]
I see it now. Beautiful!

> I assume all snapshots were created from the Flow Snapshot android app and not from the API, is that right?

Correct. The problem is with the first data point. Maybe related to me being confused about API having or not having to set an API password

**Comment by xverges** [comment]
btw, Jeremy. I have a feature request/question for the snapshot capture. Do you want me to open it here or better in https://github.com/onejgordon/flow-snapshot/issues ?

**Comment by onejgordon** [comment]
Great. If related to the UX in the app then let's put it in flow-snapshot, and for things related to analysis in the web platform, we can keep those here.
