### ISSUE TITLE
Google app engine doesn't work in some country

### ISSUE THREAD

**Issue by TonyWoo** [onejgordon/flow-dashboard#93]
Hi, because we cannot access to the google app engine, if I want to run it in my own server and save the data to MySQL, is it possible? and can you provide any recommendation to change the code for this? Thanks.

**Comment by onejgordon** [comment]
Hi @TonyWoo, sorry that you're unable to run Flow due to GAE limitations in your country. I forgot that GAE was limited in some places.

Unfortunately quite a bit of the functionality in Flow uses GAE/GCP APIs. It's certainly feasible to port it to a more flexible MySQL stack, but I'm afraid that's more work than I have capacity for at this point. 

If others would be interested in a non-GAE fork, I'd be happy to support it strategically.

**Comment by michalagata** [comment]
How about approaching it once again? I'll try to do my best, still sort of plan would be required :)
